jwt:
  token:
    header: api_key
    issuer: demo
    client-secret: restesvkl29Nvbjlsaafe
    expiry-seconds: 0
logging:
  level:
    org.springframework.security: debug
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:demo;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB